version: '3.7'

services: 
  backend:
    container_name: savvi_backend
    build: 
      context: ./backend
    ports: 
      - "8000:8000"
    restart: always
    env_file:
      - .env
    volumes:
      - static:/app/static

  frontend:
    container_name: savvi_frontend
    build: 
      context: ./frontend
    volumes:
      - frontend:/app/build

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes: 
      - static:/static
      - frontend:/var/www/frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  static:
  frontend:

