version: '3.7'

services: 

  backend:
    container_name: savvi_backend
    build: 
      context: ./backend
    ports: 
      - "8000:8000"
    env_file:
      - .env

  frontend:
    container_name: savvi_frontend
    build: 
      context: ./frontend

  caddy:
    image: caddy:latest
    restart: unless-stopped
    container_name: savvi_caddy 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend
