# Generated by Django 4.2.6 on 2024-01-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetextrequest',
            name='translated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
