# Generated by Django 4.2.6 on 2024-01-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0002_alter_translatetextrequest_translated_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_source', models.BooleanField(default=False)),
                ('is_target', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='translatetextrequest',
            old_name='text',
            new_name='input_text',
        ),
        migrations.AddField(
            model_name='translatetextrequest',
            name='input_character_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='translatetextrequest',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'SUCCESSFUL'), (0, 'FAILED')], null=True),
        ),
        migrations.AlterField(
            model_name='translatetextrequest',
            name='source_language',
            field=models.ForeignKey(limit_choices_to={'is_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='source_language_requests', to='translator.language'),
        ),
        migrations.AlterField(
            model_name='translatetextrequest',
            name='target_language',
            field=models.ForeignKey(limit_choices_to={'is_target': True}, on_delete=django.db.models.deletion.CASCADE, related_name='target_language_requests', to='translator.language'),
        ),
    ]
