# Generated by Django 4.2.6 on 2024-01-26 21:32

from django.db import migrations, models
import django.db.models.deletion
import translator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0003_language_rename_text_translatetextrequest_input_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, validators=[translator.validators.lowercase_validator]),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=30, validators=[translator.validators.lowercase_validator]),
        ),
        migrations.CreateModel(
            name='LanguageTranslationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_model', models.TextField()),
                ('source_language', models.ForeignKey(limit_choices_to={'is_source': True}, on_delete=django.db.models.deletion.CASCADE, related_name='source_language_models', to='translator.language')),
                ('target_language', models.ForeignKey(limit_choices_to={'is_target': True}, on_delete=django.db.models.deletion.CASCADE, related_name='target_language_models', to='translator.language')),
            ],
        ),
        migrations.AddField(
            model_name='translatetextrequest',
            name='model_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_name_requests', to='translator.languagetranslationmodel'),
        ),
    ]
