# Generated by Django 4.2.6 on 2024-01-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_alter_language_code_alter_language_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagetranslationmodel',
            old_name='language_model',
            new_name='model_name',
        ),
        migrations.AlterUniqueTogether(
            name='languagetranslationmodel',
            unique_together={('source_language', 'target_language')},
        ),
    ]
