# Generated by Django 4.2.6 on 2024-01-27 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0005_rename_language_model_languagetranslationmodel_model_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translatetextrequest',
            old_name='model_name',
            new_name='language_model',
        ),
    ]
