name: Build, Test, and Push Frontend Docker Image to Docker Hub

on: 
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@latest  # Update to the latest version that supports Node.js 20
    - name: Build the docker image
      run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest ./frontend

  test:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@latest  # Update to the latest version that supports Node.js 20
    - name: Test the docker image
      run: docker-compose -f frontend/docker-compose.yml up -d

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@latest  # Update to the latest version that supports Node.js 20
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

