name: Build, Test, and Push Frontend Docker Image to Docker Hub

on: 
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2  # Latest version that supports Node.js 20
      - name: Build the docker image
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest ./frontend

  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2  # Latest version that supports Node.js 20
      - name: Test the docker image
        run: docker run -d --name test-frontend -p 80:80 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2  # Latest version that supports Node.js 20

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

